version: '3'
services:
  db:
    image: postgres
    container_name: postgresql
    restart: always
    volumes:
      - "${DATA_DIR}/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: nextcloud
      POSTGRES_DB: somethingelse
      POSTGRES_USER: nextcloud

  app:
    image: nextcloud:${NEXTCLOUD_VERSION}
    container_name: nextcloud
    restart: always
    volumes:
      - "${DATA_DIR}/nextcloud:/var/www/html"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: nextcloud
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud     
    depends_on:
      - db

  web:
    build: ./web
    container_name: nginx
    restart: always
    volumes:
      - "${DATA_DIR}/nextcloud:/var/www/html:ro"
    environment: 
      VIRTUAL_HOST: ${HOST}
      LETSENCRYPT_HOST: ${HOST}
      LETSENCRYPT_EMAIL: ${EMAIL}
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs:ro"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
#      - ./nginx.conf:/etc/nginx/proxy.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - "${DATA_DIR}/nginx/certs:/etc/nginx/certs"
      - "${DATA_DIR}/nginx/vhosts:/etc/nginx/vhost.d"
      - "${DATA_DIR}/nginx/html:/usr/share/nginx/html"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

#  backups:
#    image: christophetd/duplicacy-autobackup:v1.0
#    container_name: backups
#    restart: always
#    environment:
#      BACKUP_NAME: "${BACKUP_NAME}"
#      BACKUP_LOCATION: "b2://${B2_BUCKET}"
#      BACKUP_SCHEDULE: "${BACKUP_SCHEDULE}"
#      BACKUP_ENCRYPTION_KEY: "${BACKUP_ENCRYPTION_KEY}"
#      B2_ID: "${B2_ID}"
#      B2_KEY: "${B2_KEY}"
#    volumes:
#      - "${DATA_DIR}:/data"

networks:
  proxy-tier:
